AY2223S2-CS2103-F11-3/tp

src/main/java/seedu/vms/logic/commands/patient/DeleteCommand.java, src/main/java/seedu/vms/logic/commands/patient/EditCommand.java, src/main/java/seedu/vms/ui/PersonListPanel.java, src/test/java/seedu/vms/logic/commands/patient/DeleteCommandTest.java
Resolves the following issues:
- Fix #33 
- Fix #34 
- Fix #35
- Close #17
=> Fix ID bugs

.github/workflows/gradle.yml, README.md
=> Codecov setup

src/main/java/seedu/vms/logic/parser/ParserUtil.java, src/test/java/seedu/vms/logic/parser/ParserUtilTest.java
=> Add date parser

src/main/java/seedu/vms/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/vms/logic/parser/CliSyntax.java, src/main/java/seedu/vms/logic/parser/patient/AddCommandParser.java, src/main/java/seedu/vms/logic/parser/patient/EditCommandParser.java, src/test/java/seedu/vms/logic/commands/CommandTestUtil.java, src/test/java/seedu/vms/logic/parser/ArgumentTokenizerTest.java, src/test/java/seedu/vms/logic/parser/patient/EditCommandParserTest.java, src/test/java/seedu/vms/testutil/PersonUtil.java
Resolves #54 
New sample command:
```text
patient add --n John Doe --p 98765432 --e johnd@example.com --a John street, block 123, #01-01
```
=> Update parsing to parse common delimiter

src/main/java/seedu/vms/logic/parser/ParserUtil.java, src/test/java/seedu/vms/logic/parser/ParserUtilTest.java
Related #47
#1 DOB does not keep track of birth time.
Only need `localdate`, not `localdatetime`
Waiting for #57 to merge first?
=> Add date only parser

docs/DeveloperGuide.md
After attending today's tutorial, this user story should not be a user story but a NFR instead.
Sample NFRs used in the tutorial:
=> Move potato user to NFR

src/main/java/seedu/vms/MainApp.java, src/main/java/seedu/vms/logic/Logic.java, src/main/java/seedu/vms/logic/LogicManager.java, src/main/java/seedu/vms/model/Model.java, src/main/java/seedu/vms/model/ModelManager.java, src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java, src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java, src/main/java/seedu/vms/storage/Storage.java, src/main/java/seedu/vms/storage/StorageManager.java, src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java, src/main/java/seedu/vms/storage/vaccination/VaxTypeLoader.java, src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java, src/test/java/seedu/vms/model/vaccination/VaxTypeManagerTest.java, src/test/java/seedu/vms/storage/StorageManagerTest.java, src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java, src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Resolves #70 
`VaxTypeStorage` class has been renamed to `VaxTypeManager` as I realised that "Storage" are for hard disk related classes.
Only a simple integration test is done. Test verifies that the default Pfizer dose 1 is loaded.
=> Integrate VaxTypeManager to Logic

src/main/java/seedu/vms/logic/parser/CliSyntax.java, src/main/java/seedu/vms/model/patient/Allergy.java, src/test/java/seedu/vms/model/patient/AllergyTest.java
Related to #1
Not implemented in Patient yet
Close #77
=> Add allergy

src/main/java/seedu/vms/logic/parser/CliSyntax.java, src/main/java/seedu/vms/model/patient/Allergy.java, src/main/java/seedu/vms/model/patient/Vaccine.java, src/test/java/seedu/vms/model/patient/AllergyTest.java, src/test/java/seedu/vms/model/patient/VaccineTest.java
Related to #1
Not implemented in Patient yet
Close #79
Waiting for #77 to merge first
=> Add vaccine

src/main/java/seedu/vms/ui/PatientCard.java, src/main/java/seedu/vms/ui/TagFlowView.java, src/main/java/seedu/vms/ui/vaccination/VaxTypeCard.java, src/main/resources/view/DarkTheme.css
Resolves #111 
Syncs and binds tag colors so that they can be changed easily in the future.
Removed unused code in css.
=> Sync tag colors

docs/UserGuide.md
Updated user guide to reflect new `add` command.
Resolves #115
=> Update user guide for patient add functionality

src/main/java/seedu/vms/ui/PatientCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PatientListCard.fxml, src/main/resources/view/VaxTypeCard.fxml
=> Fix patient card

src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/parser/CliSyntax.java, src/main/java/seedu/vms/logic/parser/ParserUtil.java, src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java, src/main/java/seedu/vms/model/appointment/Appointment.java
=> Complete Appointment model

src/main/java/seedu/vms/ui/appointment/AppointmentCard.java
Closes #139
Appointment card was implemented in a previous branch.
=>  Implement appointment card

src/main/java/seedu/vms/ui/PatientCard.java, src/main/resources/view/PatientListCard.fxml
=> Sync patient ID card box

src/main/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommand.java, src/main/java/seedu/vms/logic/commands/vaccination/EditVaxTypeCommand.java, src/main/java/seedu/vms/logic/parser/vaccination/AddVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/EditVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java, src/main/java/seedu/vms/logic/parser/vaccination/VaxTypeValueParser.java, src/main/java/seedu/vms/model/Model.java, src/main/java/seedu/vms/model/ModelManager.java, src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java, src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java, src/test/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommandTest.java, src/test/java/seedu/vms/logic/commands/vaccination/EditVaxTypeTest.java, src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java, src/test/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParserTest.java
Automated testing created. Almost 100% path coverage.
* Closes #87 
* Closes #88 
Will update UG in next PR.
=> Complete CRUD for vaccination

src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/commands/patient/AddCommand.java, src/main/java/seedu/vms/logic/commands/patient/DeleteCommand.java, src/main/java/seedu/vms/logic/commands/patient/EditCommand.java, src/main/java/seedu/vms/logic/commands/patient/FindCommand.java
Fix #82
Now it will look like: (pardon the crappy font problem)
=> Fix wrong command format displayed

src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java, src/main/java/seedu/vms/model/appointment/Appointment.java
=> Bugfix for invalid appointment duration

src/main/java/seedu/vms/ui/MainWindow.java, src/main/java/seedu/vms/ui/appointment/AppointmentCard.java, src/main/resources/view/AppointmentCard.fxml
Closes #181
Also added a place to display patient ID as well
=> Fix issue where Appointment ID displayed as patient ID instead of its ID

src/main/java/seedu/vms/commons/core/Messages.java, src/main/java/seedu/vms/logic/commands/appointment/DeleteCommand.java, src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java, src/main/java/seedu/vms/logic/parser/appointment/DeleteCommandParser.java, src/main/java/seedu/vms/model/Model.java, src/main/java/seedu/vms/model/ModelManager.java, src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java, src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
=> Implement delete command for appointment

docs/UserGuide.md, docs/_sass/minima/_base.scss, docs/_sass/minima/_layout.scss
I feel this presentation is neater but please do give your opinions as well.
* Closes #176
=> Update CLI presentation

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/model/FilteredIdDataMap.java, src/test/java/seedu/vms/logic/commands/vaccination/EditVaxTypeTest.java, src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Random strings that had some typos 
Fix #144
=> Fix strings

docs/UserGuide.md
* Added `add`, `delete` and `edit` commands from vaccination.
* Added vaccination attribute description.
* Added requirement description.
* Updated JSON description.
* Resolves #159
=> Update UG for vaccination

src/main/java/seedu/vms/ui/ResultDisplay.java, src/main/java/seedu/vms/ui/TagFlowView.java, src/main/resources/view/MainWindow.fxml
* Fixes #201 
* Fixes #197 
* Fixes #203
=> Fix visual bugs

docs/DeveloperGuide.md
Adds description for `LogicManager`. Description is based on #208. Diagrams later on.
* Touches on #147
=> Update DG description for `LogicManager`

docs/UserGuide.md
=> Add patient find/delete to UG

docs/DeveloperGuide.md
=> Add details about Appointment to the DG

src/main/java/seedu/vms/commons/core/Messages.java, src/main/java/seedu/vms/commons/util/StringUtil.java, src/main/java/seedu/vms/logic/commands/vaccination/FilterVaxTypeCommand.java, src/main/java/seedu/vms/logic/commands/vaccination/ListVaxTypeCommand.java, src/main/java/seedu/vms/logic/parser/FeatureParser.java, src/main/java/seedu/vms/logic/parser/vaccination/FilterVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/ListVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java, src/main/java/seedu/vms/model/FilteredIdDataMap.java, src/main/java/seedu/vms/model/FilteredMapView.java, src/main/java/seedu/vms/model/Model.java, src/main/java/seedu/vms/model/ModelManager.java, src/test/java/seedu/vms/commons/util/StringUtilTest.java, src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java, src/test/java/seedu/vms/logic/commands/vaccination/FindVaxTypeTest.java, src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
* Allows multiple filters for filtered maps (Patient and Appointments)
* Add `isMatching` method to `StringUtil` for find (can be used for Patients as well)
* Add `find` and `list` commands for vacicnation
Automated tests created for all except `List` command. Smoke tests done as well.
* Closes #89
=> Vaccination find

docs/UserGuide.md
=> Fix patient ug

src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java
=> Fix appointment checks for no existing next appointment

src/main/java/seedu/vms/logic/commands/patient/DeleteCommand.java, src/test/java/seedu/vms/logic/commands/patient/DeleteCommandTest.java, src/test/java/seedu/vms/testutil/TypicalIndexes.java
=> Fix delete patients that are not in the curr view

src/main/java/seedu/vms/logic/Logic.java, src/main/java/seedu/vms/logic/LogicManager.java, src/main/java/seedu/vms/ui/MainWindow.java
=> Fix basic commands

src/main/java/seedu/vms/model/ModelManager.java, src/main/java/seedu/vms/model/appointment/Appointment.java, src/main/java/seedu/vms/model/appointment/AppointmentManager.java
Closes #130
The handleVaccinationChange method in AppointmentManager Class:
* Deletes all occurrence of the deleted VaxType in the appointment manager.
* Replaces all occurrence of the old VaxType in the appointment manager with the new VaxType .
Closes #131
The handlePatientChange method in AppointmentManager Class deletes all occurrence of the deleted patient in the appointment manager.
=> Implement method to handle change in AppointmentManager

docs/UserGuide.md
=> Fix Patient Update UG <PATIENT_ID>

src/main/java/seedu/vms/logic/commands/vaccination/ClearVaxTypeCommand.java, src/main/java/seedu/vms/logic/parser/vaccination/ClearVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java, src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java
=> Add clear command for vaccination

src/main/java/seedu/vms/model/ModelManager.java, src/main/java/seedu/vms/model/appointment/AppointmentManager.java
=> Adds validation methods to AppointmentManager Class

docs/DeveloperGuide.md
Mainly to add the titles to avoid merge conflicts in the future.
Rest of the actual text will be edit in another PR but pls do leave your suggestions if you have any.
=> DG architecture text skeleton

src/main/java/seedu/vms/ui/vaccination/RequirementBox.java, src/main/java/seedu/vms/ui/vaccination/VaxTypeCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/RequirementBox.fxml, src/main/resources/view/VaxTypeCard.fxml
History requirements to be a list so that they are separated nicely.
=> Modify vaccination detail card

src/main/resources/view/MainWindow.fxml
Fixes resizing bug of patient detail when patient detail card is too tall
=> Fix patient detail resize bug

src/main/java/seedu/vms/commons/core/Messages.java, src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/commands/appointment/FindCommand.java, src/main/java/seedu/vms/logic/parser/CliSyntax.java, src/main/java/seedu/vms/logic/parser/ParserUtil.java, src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java, src/main/java/seedu/vms/logic/parser/appointment/FindCommandParser.java, src/main/java/seedu/vms/model/Model.java, src/main/java/seedu/vms/model/ModelManager.java, src/main/java/seedu/vms/model/appointment/predicates/EndTimePredicate.java, src/main/java/seedu/vms/model/appointment/predicates/IndexPredicate.java, src/main/java/seedu/vms/model/appointment/predicates/StartTimePredicate.java, src/main/java/seedu/vms/model/appointment/predicates/VaccineContainsKeywordsPredicate.java, src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java, src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
=> Implements FindCommand for the Appointment class

src/main/java/seedu/vms/commons/core/GuiSettings.java, src/main/java/seedu/vms/commons/core/Messages.java, src/main/java/seedu/vms/commons/util/StringUtil.java, src/main/java/seedu/vms/logic/LogicManager.java, src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/commands/patient/AddCommand.java, src/main/java/seedu/vms/logic/commands/vaccination/AddVaxTypeCommand.java, src/main/java/seedu/vms/logic/parser/ParserUtil.java, src/main/java/seedu/vms/logic/parser/vaccination/AddVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/DetailVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/EditVaxTypeParser.java, src/main/java/seedu/vms/logic/parser/vaccination/VaxTypeBuilderParser.java, src/main/java/seedu/vms/model/IdDataMap.java, src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java, src/main/java/seedu/vms/ui/ResultMessageBox.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml, src/test/java/seedu/vms/logic/parser/patient/EditCommandParserTest.java
* Fix flashing bug on start up when there is no `userprefs.json`
* Fix scroll bar occasionally showing in message box
* Standardize error messages for vaccination commands with patient and appointment
* Increase font size of messages (Vertical line characters are hard to see)
* Edit colors for warning and error messages to be slightly darker
* Closes #265
=> Standardise error message for vaccination

docs/DeveloperGuide.md
Close #153 
Close #135 
Close #150 
Feel free to edit my PR if you find anything lacking. Then approve then can merge already
=> Add paitent component, cascade delete/change into dg

src/main/java/seedu/vms/commons/core/GuiSettings.java, src/main/java/seedu/vms/logic/parser/VmsParser.java, src/main/java/seedu/vms/logic/parser/basic/BasicParser.java, src/main/java/seedu/vms/ui/HelpWindow.java, src/main/resources/view/MainWindow.fxml
* Fixes `basic` keyword not working
* Fixes help window not showing when iconified after a help command.
* Enter the help command once.
* Minimise help window to tray.
* Enter the help command again.
=> Fix basic keyword

docs/UserGuide.md, src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/commands/appointment/DeleteCommand.java, src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java, src/main/java/seedu/vms/logic/commands/appointment/FindCommand.java, src/main/java/seedu/vms/logic/commands/appointment/MarkCommand.java, src/main/java/seedu/vms/logic/commands/appointment/UnmarkCommand.java
=> Updates multiple command messages for the Appointment class

src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java
=> Fix PE-D bugs in EditCommand for Appointment class

src/main/java/seedu/vms/model/appointment/AppointmentManager.java
=> Bugfix concurrent exception when removing multiple vaccinations or patients using force

src/main/java/seedu/vms/model/IdDataMap.java, src/main/java/seedu/vms/model/StorageModel.java
=> Fix ID not resetting when cleared

src/main/java/seedu/vms/model/vaccination/VaxChecker.java
Fixes issue where the same vaccination history is used to satisfy 2 of the same requirements. This causes patient who have took only one vaccination that can clear one of the duplicate arguments to be evaluated to be able to take the vaccination. Patients that meet that requirement still work.
Behaviour was already documented in UG before PE-D.
=> Fix history requirement checks

docs/UserGuide.md, src/main/java/seedu/vms/logic/commands/patient/AddCommand.java, src/main/java/seedu/vms/logic/commands/patient/DeleteCommand.java, src/main/java/seedu/vms/logic/commands/patient/EditCommand.java, src/main/java/seedu/vms/logic/commands/patient/FindCommand.java, src/main/java/seedu/vms/logic/parser/patient/FindCommandParser.java
OLD FIND
~~NEW FIND~~
new new find
OLD EDIT
NEW EDIT
To match the UG before freeze. https://github.com/AY2223S2-CS2103-F11-3/tp/blob/d69ba11cbd28baaf74d45260fb5d35fd86fc30c0/docs/UserGuide.md
Bug as the error messages should match the command syntax of UG but its not.
=> Fix patient find/edit error messages

docs/UserGuide.md, docs/index.md, docs/team/francisyzy.md
See: #327 
May include more changes in PPP afterwards, want to merge this so that the updated project description can be reflected.
=> Update Francis PPP

docs/UserGuide.md, docs/_sass/minima/_layout.scss, src/main/java/seedu/vms/logic/LogicManager.java
Adds JSON format for all components.
Add FAQ section.
Minor formatting.
* Closes #325 
* Closes #307
=> Add JSON format to UG

src/main/java/seedu/vms/commons/core/Messages.java, src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java, src/main/java/seedu/vms/logic/commands/patient/DeleteCommand.java, src/main/java/seedu/vms/logic/commands/patient/EditCommand.java, src/test/java/seedu/vms/logic/commands/patient/DeleteCommandTest.java, src/test/java/seedu/vms/logic/commands/patient/EditCommandTest.java
=> Fix error message from index to patient_id

src/main/java/seedu/vms/commons/core/Messages.java, src/main/java/seedu/vms/logic/parser/ParserUtil.java, src/main/java/seedu/vms/model/keyword/Keyword.java
=> Fix bug of 'keyword' as subkeyword

docs/UserGuide.md
=> Add <keyword> in Types

docs/team/nuse0726844.md
=> Updates the PPP for nusE0726844

docs/UserGuide.md, docs/_sass/minima/_base.scss, docs/_sass/minima/custom-styles.scss
Changes:
* Added planned features section.
* Added color description of vaccination requirement tags.
* Standardised command short description to sound more like a command.
* Added validation warning for patient and vaccination edit and appointment unmark.
* Made headings mroe prominent.
=> UG update and standardisation

src/main/java/seedu/vms/commons/util/JsonUtil.java, src/main/java/seedu/vms/commons/util/StringUtil.java, src/main/java/seedu/vms/logic/Logic.java, src/main/java/seedu/vms/logic/LogicManager.java, src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java, src/main/java/seedu/vms/logic/commands/appointment/UnmarkCommand.java, src/main/java/seedu/vms/logic/parser/ParserUtil.java, src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java, src/main/java/seedu/vms/logic/parser/patient/AddCommandParser.java, src/main/java/seedu/vms/logic/parser/patient/DeleteCommandParser.java, src/main/java/seedu/vms/model/FilteredIdDataMap.java, src/main/java/seedu/vms/model/IdData.java, src/main/java/seedu/vms/model/IdDataMap.java, src/main/java/seedu/vms/model/Model.java, src/main/java/seedu/vms/model/ModelManager.java, src/main/java/seedu/vms/model/StorageModel.java, src/main/java/seedu/vms/model/vaccination/Requirement.java, src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java, src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java, src/main/java/seedu/vms/storage/JsonAdaptedGroupName.java, src/main/java/seedu/vms/storage/appointment/JsonSerializableAppointmentManager.java, src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java, src/main/java/seedu/vms/ui/MainWindow.java, src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java, src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Mostly corrected documentations.
Updated authorship of code that I do think I should take credit for as well.
=> Refactor code

docs/UserGuide.md
Fix #346 
See #343, not sure if its a fix for 343 or should I write it in the DG for planned enhancements
=> Fix ug patient

docs/AboutUs.md, docs/DeveloperGuide.md, docs/team/francisyzy.md
=> Fix DG formatting and complete Francis PPP

docs/UserGuide.md
=> Minor tip edits

docs/team/daitenshionyan.md
=> Finish PPP
